name: Release on PyPI

on:
  push:
    tags:
    - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
      provider: pypi
      user: __token__
      password: ${{ secrets.PYPI_PASSWORD }}
