name: Tox tests

on: [push, pull_request]

jobs:
  py27:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py27
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e static
  py36-pidiff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e pidiff
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm
          #- name: Install system dependencies
          #run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
          #- name: Install pytest cov
          #run: pip install pytest-cov
      - name: Run Tox
        run: tox -e cov
          #- name: Validate codecov yaml
          #run: cat codecov.yml | curl --data-binary @- https://codecov.io/validate
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          #token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: |
          tox -e docs
          scripts/push-docs
  py36-revdep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: |
          sudo apt-get install -y rpm
          sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e revdep-pubtools-pulp
