name: Tox tests

on: [push, pull_request]

jobs:
  py27:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intsall RPm
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py27
        if: job.status == 'success'
        run: test 2.7 = docs && scripts/push-docs
  py36:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intsall RPm
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: static
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e static
        if: job.status == 'success'
        run: test static = docs && scripts/push-docs
  py36:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intsall RPm
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: pidiff
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e pidiff
        if: job.status == 'success'
        run: test pidiff = docs && scripts/push-docs
  py36:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intsall RPm
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6 DEPLOY=1
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e cov DEPLOY=1
        if: job.status == 'success'
        run: test cov = docs && scripts/push-docs
  py36:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intsall RPm
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: docs
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs
        if: job.status == 'success'
        run: test docs = docs && scripts/push-docs
  py36:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intsall RPm
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: revdep-pubtools-pulp
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e revdep-pubtools-pulp
        if: job.status == 'success'
        run: test revdep-pubtools-pulp = docs && scripts/push-docs
